---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"

  - package-ecosystem: "docker"
    directories:
      - "/docusaurus-docs"
      - "/ferretdb-prettier"
      - "/ferretdb-reprepro"
      - "/ferretdb-textlint"
      - "/ferretdb-wrangler"
      - "/legacy-mongo-shell"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"

  - package-ecosystem: "npm"
    directory: "/docusaurus-docs"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"
    allow:
      - dependency-name: "@docusaurus/*"

  - package-ecosystem: "npm"
    directories:
      - "/ferretdb-prettier"
      - "/ferretdb-textlint"
      - "/ferretdb-wrangler"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"
