---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"

  - package-ecosystem: "docker"
    directory: "/docusaurus-docs"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"
  - package-ecosystem: "npm"
    directory: "/docusaurus-docs"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"
    allow:
      - dependency-name: "@docusaurus/*"

  - package-ecosystem: "docker"
    directory: "/ferretdb-textlint"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"
  - package-ecosystem: "npm"
    directory: "/ferretdb-textlint"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"

  - package-ecosystem: "docker"
    directory: "/ferretdb-wrangler"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"
  - package-ecosystem: "npm"
    directory: "/ferretdb-wrangler"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"

  - package-ecosystem: "docker"
    directory: "/golang"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"

  - package-ecosystem: "docker"
    directory: "/legacy-mongo-shell"
    labels: [deps]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:42"
